#%RAML 1.0
title: events
version: 1
baseUri: http://localhost:8080
protocols: [ "HTTP" ]
mediaType: application/json
types:
    User:
        type: object
        properties:
            first_name: string
            last_name: string
            email: string
/users:
    /{id}:
        put:
            description: |
                Изменяет данные пользователя. Может быть переданы некоторые поля пользователя которые должны быть обновлены.
                Возвращает success:true или одну из ошибок:

                1. INVALID_PARAMS
                2. USER_NOT_FOUND
            body:
                application/json:
                    example: |
                        { "first_name": "Bill" }
            responses:
                400:
                    application/json:
                        example: |
                            { "error": "INVALID_PARAMS", "first_name": "Must be a string." }
                200:
                    application/json:
                        example: { "success": true }
        /events:
            post:
                description: |
                    Привязывает пользователя к событию.
                    Возвращает success:true или одну из ошибок:
                    
                    1. USER_NOT_FOUND
                    2. EVENT_NOT_FOUND

                    _Если пользователь уже является участником этого события, то просто возвращается успешный ответ._
                body:
                    application/json:
                        example: |
                            {"event_id": 1}
                responses:
                    400:
                        application/json:
                            example: |
                                {"error": "USER_NOT_FOUND"}
                    200:
                        application/json:
                            example: |
                                {"success": true}
            delete:
                description: |
                    Удаляет пользователя из списка участников мероприятия __event_id__.
                    Возвращает __success:true__ или одну из ошибок:

                    1. USER_NOT_FOUND
                    2. EVENT_NOT_FOUND

                    _Если пользователь не является участником этого события, то просто возвращается успешный ответ._
                body:
                    application/json:
                        example: |
                            {"event_id": 1}
                responses:
                    400:
                        application/json:
                            example: |
                                {"error": "USER_NOT_FOUND"}
                    200:
                        application/json:
                            example: |
                                {"success": true}
    get:
        description: Возвращает пользователей.
        queryParameters:
            event_id:
                description: ID события
                required: false
                type: int
                example: 1
            limit:
                required: false,
                type: int,
                example: 20,
                default: 50
            page:
                required: false,
                type: int,
                example: 1,
                default: 1
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [
                                {
                                    "first_name": "John",
                                    "last_name": "Bay",
                                    "email": "test@mail.com"
                                }
                            ]
    post:
        description: |
            Добавляет нового пользователя.
            Возвращает success:true или одну из ошибок:

            1. INVALID_PARAMS
            2. EMAIL_ALREADY_EXIST
        body:
            application/json:
                type: User
        responses:
            200:
                application/json:
                    example: |
                        {"id": 2}
            400:
                application/json:
                    example: |
                        { "error": "INVALID_PARAMS", "fist_name": "Is required." }
    delete:
        desсription: Удаляет пользователя по ID.
        body:
            application/json:
                example: |
                    { "id": 2 }
        responses:
            200:
                application/json:
                    example: |
                        { "success": true }