####################################################################################################
# Creating container MySQL
####################################################################################################
mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes:
        - ./image/mysql/data/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: usr
        MYSQL_PASSWORD: usr-password
        MYSQL_DATABASE: event-service

####################################################################################################
# Creating container PHP
####################################################################################################
app:
    build: ./image/php/
    ports:
        - "9000:9000"
    volumes:
        - ./src:/var/www/html
    links:
        - mysql
    command: /bin/bash -c "/wait && composer install && ln -s -f .env.production .env && php artisan migrate --force && /usr/bin/supervisord"
    environment:
        WAIT_HOSTS: mysql:3306
        WAIT_HOSTS_TIMEOUT: 60
    
####################################################################################################
# Creating container (Nginx)
####################################################################################################
nginx:
    image: nginx:latest
    ports:
        - 8080:80
    volumes:
        - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app